/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tsuyogoro_nativetest_NativeManger */

#ifndef _Included_com_tsuyogoro_nativetest_NativeManger
#define _Included_com_tsuyogoro_nativetest_NativeManger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tsuyogoro_nativetest_NativeManger
 * Method:    msgFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tsuyogoro_nativetest_NativeManger_msgFromNDK
  (JNIEnv *, jobject);

/*
 * Class:     com_tsuyogoro_nativetest_NativeManger
 * Method:    createDataType
 * Signature: (ILjava/lang/String;)Lcom/tsuyogoro/nativetest/DataType;
 */
//JNIEXPORT jobject JNICALL Java_com_tsuyogoro_nativetest_NativeManger_createDataType
//  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_tsuyogoro_nativetest_NativeManger
 * Method:    seeDataType
 * Signature: (Lcom/tsuyogoro/nativetest/DataType;)V
 */
JNIEXPORT void JNICALL Java_com_tsuyogoro_nativetest_NativeManger_seeDataType
  (JNIEnv *, jobject, jobject dataType);

#ifdef __cplusplus
}
#endif
#endif
